version: "3.6"

services:
    app:
        build: .
        image: app:latest
        volumes:
            - ./logs/:/logs/
        ports:
            - 8080:8080

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        volumes:
            - ./resources/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        healthcheck:
            test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
            interval: 3s
            timeout: 3s
            retries: 10
        ports:
            - 9200:9200

    logstash:
        image: docker.elastic.co/logstash/logstash:7.6.2
        volumes:
            - ./resources/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
        depends_on:
            elasticsearch:
                condition: service_healthy

    filebeat:
        image: docker.elastic.co/beats/filebeat:6.5.1
        depends_on:
            elasticsearch:
                condition: service_healthy
        volumes:
            - ./resources/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./logs/:/logs/

    kibana:
        image: docker.elastic.co/kibana/kibana:7.6.2
        depends_on:
            elasticsearch:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
            interval: 3s
            timeout: 3s
            retries: 50
        ports:
            - 5601:5601
